/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 arvr.gltf --transform
Author: cestunchopin (https://sketchfab.com/cestunchopin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moli-xavi-eclipse13-26b8e04887ad4c8d8702f7e898081ce4
Title: MOLI XAVI ECLIPSE13
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/arvr-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.02, 0, 0.24]} rotation={[-Math.PI, 0.02, 3.12]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material_0.002']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material_0.002']} />
      </group>
      <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} position={[0.02, -0.36, 0.24]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Material.002']} position={[0.02, -0.38, -0.17]} rotation={[0, 0, -Math.PI]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['Material.002']} position={[0.02, -0.38, -0.05]} rotation={[0, 0, -Math.PI]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['Material.002']} position={[0.02, -0.38, -0.07]} rotation={[0, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/arvr-transformed.glb')
