/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 java.gltf --transform
Author: PhantomXD (https://sketchfab.com/PhantomXD)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/java-442de0f1b8a54966bc16466b329105af
Title: Java
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/java-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Cube">
              <mesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={materials.Material} />
            </group>
            <group name="Plane" position={[0.79, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials.Material} />
            </group>
            <group name="Plane001" position={[0, 0, 1.52]} rotation={[Math.PI / 2, 0, 0]} scale={1.22}>
              <mesh name="Plane001_0" geometry={nodes.Plane001_0.geometry} material={materials['Material.002']} morphTargetDictionary={nodes.Plane001_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane001_0.morphTargetInfluences} />
            </group>
            <group name="Torus001" position={[-0.14, -0.06, -0.77]} rotation={[-0.14, -0.02, 0.1]} scale={[0.47, 0.43, 0.43]}>
              <mesh name="Torus001_0" geometry={nodes.Torus001_0.geometry} material={materials.Material} />
            </group>
            <group name="Torus000" position={[0.1, -0.03, -0.88]} rotation={[-0.13, -0.05, 0.1]} scale={[0.45, 0.42, 0.3]}>
              <mesh name="Torus000_0" geometry={nodes.Torus000_0.geometry} material={materials.Material} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/java-transformed.glb')
