/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 open.gltf --transform
Author: _surovic_ (https://sketchfab.com/samuelsurovic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/geforce-rtx-3080-graphics-card-8b947ee1bf7a4e3d8ffa1c24893ac160
Title: GeForce RTX 3080 Graphics Card
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/open-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
          <group name="8e0b9a820c0540d88390810ccb0e8d07fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="heatsink_front">
                    <mesh name="heatsink_front_RTX_3080_0" geometry={nodes.heatsink_front_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="motherboard">
                    <mesh name="motherboard_RTX_3080_0" geometry={nodes.motherboard_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="back_shield">
                    <mesh name="back_shield_RTX_3080_0" geometry={nodes.back_shield_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="cover">
                    <mesh name="cover_RTX_3080_0" geometry={nodes.cover_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="ports">
                    <mesh name="ports_RTX_3080_0" geometry={nodes.ports_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="cover_right">
                    <mesh name="cover_right_RTX_3080_0" geometry={nodes.cover_right_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="cover_left">
                    <mesh name="cover_left_RTX_3080_0" geometry={nodes.cover_left_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="heatsink_right">
                    <mesh name="heatsink_right_RTX_3080_0" geometry={nodes.heatsink_right_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="heatsink_left">
                    <mesh name="heatsink_left_RTX_3080_0" geometry={nodes.heatsink_left_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="screw">
                    <mesh name="screw_RTX_3080_0" geometry={nodes.screw_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="12_pin">
                    <mesh name="12_pin_RTX_3080_0" geometry={nodes['12_pin_RTX_3080_0'].geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="heatpipes">
                    <mesh name="heatpipes_RTX_3080_0" geometry={nodes.heatpipes_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="fan_holder">
                    <mesh name="fan_holder_RTX_3080_0" geometry={nodes.fan_holder_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="fan_ring_2">
                    <mesh name="fan_ring_2_RTX_3080_0" geometry={nodes.fan_ring_2_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="heatsink_back">
                    <mesh name="heatsink_back_RTX_3080_0" geometry={nodes.heatsink_back_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="coldplate">
                    <mesh name="coldplate_RTX_3080_0" geometry={nodes.coldplate_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="fan_ring_2001">
                    <mesh name="fan_ring_2001_RTX_3080_0" geometry={nodes.fan_ring_2001_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="screw_2001">
                    <mesh name="screw_2001_RTX_3080_0" geometry={nodes.screw_2001_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="screw_2002">
                    <mesh name="screw_2002_RTX_3080_0" geometry={nodes.screw_2002_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="screw_2003">
                    <mesh name="screw_2003_RTX_3080_0" geometry={nodes.screw_2003_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="screw_2004">
                    <mesh name="screw_2004_RTX_3080_0" geometry={nodes.screw_2004_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="screw001">
                    <mesh name="screw001_RTX_3080_0" geometry={nodes.screw001_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="body001">
                    <mesh name="body001_RTX_3080_0" geometry={nodes.body001_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="fan_holder_2">
                    <mesh name="fan_holder_2_RTX_3080_0" geometry={nodes.fan_holder_2_RTX_3080_0.geometry} material={materials.RTX_3080} />
                  </group>
                  <group name="Armature">
                    <group name="Object_55">
                      <group name="_rootJoint">
                        <group name="Bone001_01" position={[0.09, 0, 0.04]} rotation={[Math.PI / 2, 0.74, 0]}>
                          <group name="fan" rotation={[-Math.PI / 2, 0, 2.62]}>
                            <mesh name="fan_RTX_3080_0" geometry={nodes.fan_RTX_3080_0.geometry} material={materials.RTX_3080} />
                          </group>
                        </group>
                        <group name="Bone002_02" position={[-0.09, 0, 0]} rotation={[Math.PI / 2, -0.83, -Math.PI]}>
                          <group name="fan_2" rotation={[Math.PI / 2, 0, 0.98]}>
                            <mesh name="fan_2_RTX_3080_0" geometry={nodes.fan_2_RTX_3080_0.geometry} material={materials.RTX_3080} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <mesh name="body_RTX_3080_0" geometry={nodes.body_RTX_3080_0.geometry} material={materials.RTX_3080} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/open-transformed.glb')
