/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ser.gltf --transform
Author: gav.grant (https://sketchfab.com/gav.grant)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/server-cabinet-test-argos-5532b05f53504abeb8fb8646a6a68e16
Title: Server Cabinet test - Argos
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ser-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.1267']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.7978']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.7978']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.7978']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.7981']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.7982']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.7978']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.7978']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.7981']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.7988']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.7989']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.7990']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.7993']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.7994']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.7983']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Material.7983']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.7993']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ser-transformed.glb')
